#docker-compose build --no-cache 
version: "3"
services:
  nginx:
    image: nginx
    container_name: docker_nginx
    #restart: always
    links:
      - php
    volumes:
      - ./Projects/:/var/www/html/:ro
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - 8000:80
    
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker_php
    volumes:
      - ./Projects:/var/www/html/
    tmpfs: /tmp
    depends_on:
      - mariadb
    links:
      - mariadb 

  mariadb:
    image: mariadb:latest
    container_name: docker_mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIA_DB_ROOT_PWD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIA_DB_USER_PWD} 
    volumes:
      - ./db/:/var/lib/mysql/
      
  phpmyadmin:
    image: phpmyadmin
    container_name: docker_phpmyadmin
    ports:
      - 9000:80
    links:
      - mariadb:db

